[[redirects]]
  from = "/*"
  to = "https://xcam-app.aserio.workers.dev/player/:splat"
  status = 200
  force = true
    [redirects.headers]
    Access-Control-Allow-Origin = ""
    Access-Control-Allow-Headers = ""
    Access-Control-Allow-Methods = ""
    Access-Control-Allow-Credentials = ""
    Vary = ""