# === Configuração do Worker Cloudflare ===
name = "xcam"
main = "index.js"
compatibility_date = "2024-05-01"
workers_dev = true
route = ""
account_id = "962d0bd07aad1f73db41e18f45cb7470"

# === Redirecionamento via Netlify com bloqueio de cabeçalhos CORS ===
[[redirects]]
  from = "/*"
  to = "https://xcam.aserio.workers.dev/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = ""
    Access-Control-Allow-Headers = ""
    Access-Control-Allow-Methods = ""
    Access-Control-Allow-Credentials = ""
    Vary = ""